POST https://faktury-backend.herokuapp.com/api/signup
content-type: application/json

{
  "login": "email@email.com",
  "password": "password123",
  "company": {
    "id": "string",
    "name": "Media Saturn Online Sp. z o.o.",
    "nip": "1234567890",
    "firstAddressLine": "Al. Jerozolimskie 179, 02-222 Warszawa.",
    "secondAddressLine": "Budynek B2, piętro 6",
    "info": "tel. 123 456 789, email: email@email.com",
    "bankName": "ALIOR BANK SA",
    "bankAccountNumber": "PL12 3456 0000 0000 0000 0000 7890"
  },
  "roles": [
    "string"
  ],
  
}

###
POST https://faktury-backend.herokuapp.com/api/login
accept: application/json
content-type: application/json

{
  "login": "email@email.com",
  "password": "password123",
}
