export const ADD_CONTRACTOR_REQUEST = 'ADD_CONTRACTOR_REQUEST'
export const ADD_CONTRACTOR_SUCCESS = 'ADD_CONTRACTOR_SUCCESS'
export const ADD_CONTRACTOR_FAIL = 'ADD_CONTRACTOR_FAIL'

export const DELETE_CONTRACTOR_REQUEST = 'DELETE_CONTRACTOR_REQUEST'
export const DELETE_CONTRACTOR_SUCCESS = 'DELETE_CONTRACTOR_SUCCESS'
export const DELETE_CONTRACTOR_FAIL = 'DELETE_CONTRACTOR_FAIL'

export const EDIT_CONTRACTOR_REQUEST = 'EDIT_CONTRACTOR_REQUEST'
export const EDIT_CONTRACTOR_SUCCESS = 'EDIT_CONTRACTOR_SUCCESS'
export const EDIT_CONTRACTOR_FAIL = 'EDIT_CONTRACTOR_FAIL'

export const GET_CONTRACTORS_REQUEST = 'GET_CONTRACTORS_REQUEST'
export const GET_CONTRACTORS_SUCCESS = 'GET_CONTRACTORS_SUCCESS'
export const GET_CONTRACTORS_FAIL = 'GET_CONTRACTORS_FAIL'

export const GET_CONTRACTOR_DETAILS_REQUEST = 'GET_CONTRACTOR_DETAILS_REQUEST'
export const GET_CONTRACTOR_DETAILS_SUCCESS = 'GET_CONTRACTOR_DETAILS_SUCCESS'
export const GET_CONTRACTOR_DETAILS_FAIL = 'GET_CONTRACTOR_DETAILS_FAIL'