export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST'
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS'
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL'

export const GET_INVOICE_PDF_REQUEST = 'GET_INVOICE_PDF_REQUEST'
export const GET_INVOICE_PDF_SUCCESS = 'GET_INVOICE_PDF_SUCCESS'
export const GET_INVOICE_PDF_FAIL = 'GET_INVOICE_PDF_FAIL'

export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST'
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS'
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL'

export const GET_INVOICE_DETAILS_REQUEST = 'GET_INVOICE_DETAILS_REQUEST'
export const GET_INVOICE_DETAILS_SUCCESS = 'GET_INVOICE_DETAILS_SUCCESS'
export const GET_INVOICE_DETAILS_FAIL = 'GET_INVOICE_DETAILS_FAIL'

export const EDIT_INVOICE_REQUEST = 'EDIT_INVOICE_REQUEST'
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS'
export const EDIT_INVOICE_FAIL = 'EDIT_INVOICE_FAIL'

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST'
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS'
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL'