export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST'
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS'
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL'

export const EDIT_SELLER_DATA_REQUEST = 'EDIT_SELLER_DATA_REQUEST'
export const EDIT_SELLER_DATA_SUCCESS = 'EDIT_SELLER_DATA_SUCCESS'
export const EDIT_SELLER_DATA_FAIL = 'EDIT_SELLER_DATA_FAIL'

export const ADD_INVOICE_ENTRY_REQUEST = 'ADD_INVOICE_ENTRY_REQUEST'
export const ADD_INVOICE_ENTRY_SUCCESS = 'ADD_INVOICE_ENTRY_SUCCESS'
export const ADD_INVOICE_ENTRY_FAIL = 'ADD_INVOICE_ENTRY_FAIL'

export const ADD_INVOICE_ENTRY_REQUEST = 'ADD_INVOICE_ENTRY_REQUEST'
export const ADD_INVOICE_ENTRY_SUCCESS = 'ADD_INVOICE_ENTRY_SUCCESS'
export const ADD_INVOICE_ENTRY_FAIL = 'ADD_INVOICE_ENTRY_FAIL'